# Generated by Django 6.0.2 on 2026-03-03 13:43

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyInformation',
            fields=[
                ('company_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('company_name', models.CharField(max_length=250)),
                ('email_id', models.EmailField(max_length=254, unique=True)),
                ('contact_number', models.CharField(max_length=15, unique=True)),
                ('address', models.TextField()),
                ('is_company_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PlanInformation',
            fields=[
                ('plan_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('plan_name', models.CharField(max_length=100, unique=True)),
                ('plan_price', models.DecimalField(db_comment='In Rupees', decimal_places=2, max_digits=10)),
                ('monthly_request_limit', models.BigIntegerField()),
                ('requests_per_minute', models.BigIntegerField()),
                ('requests_per_hour', models.BigIntegerField()),
                ('requests_per_day', models.BigIntegerField()),
                ('plan_status', models.SmallIntegerField(db_comment='(1=active, 2=inactive, 3=paused)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('user_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=128)),
                ('phone_number', models.CharField(max_length=10, unique=True)),
                ('role', models.SmallIntegerField(db_comment='(1=superadmin, 2=admin, 3=readonly)')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee_id', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='KeyInformation',
            fields=[
                ('key_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('key_value', models.CharField(max_length=64, unique=True)),
                ('activation_time', models.DateTimeField(db_comment='provided by the issuer')),
                ('valid_till', models.DateTimeField()),
                ('last_used_at', models.DateTimeField(null=True)),
                ('key_status', models.SmallIntegerField(db_comment='(1=active, 2=inactive, 3=paused)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.companyinformation')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('plan_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.planinformation')),
            ],
        ),
        migrations.CreateModel(
            name='KeyUtilizationInfo',
            fields=[
                ('key_info_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('request_datetime', models.DateTimeField()),
                ('endpoint', models.CharField()),
                ('ip_address', models.GenericIPAddressField()),
                ('response_status', models.SmallIntegerField(db_comment='(1=success, 2=failure, 3=pending)')),
                ('response_time_ms', models.BigIntegerField()),
                ('key_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.keyinformation')),
            ],
        ),
    ]
