# Generated by Django 6.0.2 on 2026-03-11 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.SmallIntegerField(db_comment='(1=superadmin, 2=admin, 3=readonly)', default=2),
        ),
        migrations.AlterField(
            model_name='keyinformation',
            name='key_status',
            field=models.SmallIntegerField(db_comment='(1=active, 2=inactive, 3=paused)', default=2),
        ),
        migrations.AlterField(
            model_name='planinformation',
            name='monthly_request_limit',
            field=models.BigIntegerField(default=100000),
        ),
        migrations.AlterField(
            model_name='planinformation',
            name='plan_status',
            field=models.SmallIntegerField(db_comment='(1=active, 2=inactive, 3=paused)', default=2),
        ),
        migrations.AlterField(
            model_name='planinformation',
            name='requests_per_day',
            field=models.BigIntegerField(default=10000),
        ),
        migrations.AlterField(
            model_name='planinformation',
            name='requests_per_hour',
            field=models.BigIntegerField(default=1000),
        ),
        migrations.AlterField(
            model_name='planinformation',
            name='requests_per_minute',
            field=models.BigIntegerField(default=100),
        ),
    ]
