# Generated by Django 6.0.2 on 2026-03-11 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_customuser_role_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='keyutilizationinfo',
            old_name='key_id',
            new_name='key',
        ),
    ]
