# Generated by Django 6.0.2 on 2026-03-11 10:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_key_id_keyutilizationinfo_key'),
    ]

    operations = [
        migrations.RenameField(
            model_name='keyinformation',
            old_name='company_id',
            new_name='company',
        ),
        migrations.RenameField(
            model_name='keyinformation',
            old_name='plan_id',
            new_name='plan',
        ),
        migrations.AlterField(
            model_name='keyinformation',
            name='created_by',
            field=models.ForeignKey(db_column='created_by', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
