# Generated by Django 6.0.2 on 2026-03-11 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_rename_company_id_keyinformation_company_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='last_login',
            field=models.DateTimeField(null=True),
        ),
    ]
