# Generated by Django 6.0.2 on 2026-03-11 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_customuser_last_login'),
    ]

    operations = [
        migrations.RenameField(
            model_name='keyinformation',
            old_name='company',
            new_name='company_id',
        ),
        migrations.RenameField(
            model_name='keyinformation',
            old_name='plan',
            new_name='plan_id',
        ),
        migrations.RenameField(
            model_name='keyutilizationinfo',
            old_name='key',
            new_name='key_id',
        ),
    ]
