# Generated by Django 6.0.2 on 2026-03-11 12:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_rename_company_keyinformation_company_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keyinformation',
            name='company_id',
            field=models.ForeignKey(db_column='company_id', on_delete=django.db.models.deletion.PROTECT, to='core.companyinformation'),
        ),
        migrations.AlterField(
            model_name='keyinformation',
            name='plan_id',
            field=models.ForeignKey(db_column='plan_id', on_delete=django.db.models.deletion.PROTECT, to='core.planinformation'),
        ),
        migrations.AlterField(
            model_name='keyutilizationinfo',
            name='key_id',
            field=models.ForeignKey(db_column='key_id', on_delete=django.db.models.deletion.PROTECT, to='core.keyinformation'),
        ),
    ]
