# Generated by Django 6.0.2 on 2026-03-11 18:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_keyinformation_company_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='company_id',
            field=models.ForeignKey(blank=True, db_column='company_id', null=True, on_delete=django.db.models.deletion.PROTECT, to='core.companyinformation'),
        ),
    ]
