# Generated by Django 6.0.2 on 2026-04-01 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_customuser_company_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='planinformation',
            old_name='monthly_request_limit',
            new_name='requests_per_month',
        ),
    ]
