from rest_framework.serializers import ModelSerializer
from core.models import KeyInformation

class CreateAPIKeySerializer(ModelSerializer):

    class Meta:
        model = KeyInformation
        fields = ["key_id", "key_status", "key_value", "company_id", "plan_id", "activation_datetime", "valid_till","created_by"]
        
        read_only_fields = ["key_id", "key_status", "created_by"] # these fields will be generated by system and not provided by user
        extra_kwargs = {"key_value": {"write_only": True}} # this ensures that hashed key is not exposed in any API response, it can only be used for writing to database
            